# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: avod/protos/mini_batch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='avod/protos/mini_batch.proto',
  package='avod.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x61vod/protos/mini_batch.proto\x12\x0b\x61vod.protos\"\x98\x01\n\x0fMiniBatchConfig\x12\x19\n\x11\x64\x65nsity_threshold\x18\x01 \x02(\x05\x12\x33\n\nrpn_config\x18\x02 \x02(\x0b\x32\x1f.avod.protos.MiniBatchRpnConfig\x12\x35\n\x0b\x61vod_config\x18\x03 \x02(\x0b\x32 .avod.protos.MiniBatchAvodConfig\"h\n\x16MiniBatchIouThresholds\x12\x12\n\nneg_iou_lo\x18\x03 \x02(\x02\x12\x12\n\nneg_iou_hi\x18\x04 \x02(\x02\x12\x12\n\npos_iou_lo\x18\x05 \x02(\x02\x12\x12\n\npos_iou_hi\x18\x06 \x02(\x02\"\xbd\x01\n\x12MiniBatchRpnConfig\x12@\n\x11iou_2d_thresholds\x18\x01 \x01(\x0b\x32#.avod.protos.MiniBatchIouThresholdsH\x00\x12@\n\x11iou_3d_thresholds\x18\x02 \x01(\x0b\x32#.avod.protos.MiniBatchIouThresholdsH\x00\x12\x17\n\x0fmini_batch_size\x18\x03 \x02(\x05\x42\n\n\x08iou_type\"n\n\x13MiniBatchAvodConfig\x12>\n\x11iou_2d_thresholds\x18\x01 \x02(\x0b\x32#.avod.protos.MiniBatchIouThresholds\x12\x17\n\x0fmini_batch_size\x18\x02 \x02(\x05')
)




_MINIBATCHCONFIG = _descriptor.Descriptor(
  name='MiniBatchConfig',
  full_name='avod.protos.MiniBatchConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='density_threshold', full_name='avod.protos.MiniBatchConfig.density_threshold', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpn_config', full_name='avod.protos.MiniBatchConfig.rpn_config', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avod_config', full_name='avod.protos.MiniBatchConfig.avod_config', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=198,
)


_MINIBATCHIOUTHRESHOLDS = _descriptor.Descriptor(
  name='MiniBatchIouThresholds',
  full_name='avod.protos.MiniBatchIouThresholds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neg_iou_lo', full_name='avod.protos.MiniBatchIouThresholds.neg_iou_lo', index=0,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neg_iou_hi', full_name='avod.protos.MiniBatchIouThresholds.neg_iou_hi', index=1,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_iou_lo', full_name='avod.protos.MiniBatchIouThresholds.pos_iou_lo', index=2,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_iou_hi', full_name='avod.protos.MiniBatchIouThresholds.pos_iou_hi', index=3,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=304,
)


_MINIBATCHRPNCONFIG = _descriptor.Descriptor(
  name='MiniBatchRpnConfig',
  full_name='avod.protos.MiniBatchRpnConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iou_2d_thresholds', full_name='avod.protos.MiniBatchRpnConfig.iou_2d_thresholds', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iou_3d_thresholds', full_name='avod.protos.MiniBatchRpnConfig.iou_3d_thresholds', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mini_batch_size', full_name='avod.protos.MiniBatchRpnConfig.mini_batch_size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='iou_type', full_name='avod.protos.MiniBatchRpnConfig.iou_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=307,
  serialized_end=496,
)


_MINIBATCHAVODCONFIG = _descriptor.Descriptor(
  name='MiniBatchAvodConfig',
  full_name='avod.protos.MiniBatchAvodConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iou_2d_thresholds', full_name='avod.protos.MiniBatchAvodConfig.iou_2d_thresholds', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mini_batch_size', full_name='avod.protos.MiniBatchAvodConfig.mini_batch_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=608,
)

_MINIBATCHCONFIG.fields_by_name['rpn_config'].message_type = _MINIBATCHRPNCONFIG
_MINIBATCHCONFIG.fields_by_name['avod_config'].message_type = _MINIBATCHAVODCONFIG
_MINIBATCHRPNCONFIG.fields_by_name['iou_2d_thresholds'].message_type = _MINIBATCHIOUTHRESHOLDS
_MINIBATCHRPNCONFIG.fields_by_name['iou_3d_thresholds'].message_type = _MINIBATCHIOUTHRESHOLDS
_MINIBATCHRPNCONFIG.oneofs_by_name['iou_type'].fields.append(
  _MINIBATCHRPNCONFIG.fields_by_name['iou_2d_thresholds'])
_MINIBATCHRPNCONFIG.fields_by_name['iou_2d_thresholds'].containing_oneof = _MINIBATCHRPNCONFIG.oneofs_by_name['iou_type']
_MINIBATCHRPNCONFIG.oneofs_by_name['iou_type'].fields.append(
  _MINIBATCHRPNCONFIG.fields_by_name['iou_3d_thresholds'])
_MINIBATCHRPNCONFIG.fields_by_name['iou_3d_thresholds'].containing_oneof = _MINIBATCHRPNCONFIG.oneofs_by_name['iou_type']
_MINIBATCHAVODCONFIG.fields_by_name['iou_2d_thresholds'].message_type = _MINIBATCHIOUTHRESHOLDS
DESCRIPTOR.message_types_by_name['MiniBatchConfig'] = _MINIBATCHCONFIG
DESCRIPTOR.message_types_by_name['MiniBatchIouThresholds'] = _MINIBATCHIOUTHRESHOLDS
DESCRIPTOR.message_types_by_name['MiniBatchRpnConfig'] = _MINIBATCHRPNCONFIG
DESCRIPTOR.message_types_by_name['MiniBatchAvodConfig'] = _MINIBATCHAVODCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MiniBatchConfig = _reflection.GeneratedProtocolMessageType('MiniBatchConfig', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHCONFIG,
  __module__ = 'avod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:avod.protos.MiniBatchConfig)
  ))
_sym_db.RegisterMessage(MiniBatchConfig)

MiniBatchIouThresholds = _reflection.GeneratedProtocolMessageType('MiniBatchIouThresholds', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHIOUTHRESHOLDS,
  __module__ = 'avod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:avod.protos.MiniBatchIouThresholds)
  ))
_sym_db.RegisterMessage(MiniBatchIouThresholds)

MiniBatchRpnConfig = _reflection.GeneratedProtocolMessageType('MiniBatchRpnConfig', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHRPNCONFIG,
  __module__ = 'avod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:avod.protos.MiniBatchRpnConfig)
  ))
_sym_db.RegisterMessage(MiniBatchRpnConfig)

MiniBatchAvodConfig = _reflection.GeneratedProtocolMessageType('MiniBatchAvodConfig', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHAVODCONFIG,
  __module__ = 'avod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:avod.protos.MiniBatchAvodConfig)
  ))
_sym_db.RegisterMessage(MiniBatchAvodConfig)


# @@protoc_insertion_point(module_scope)
